AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 110
